### ISSUE TITLE
Major flaws

### ISSUE THREAD

**Issue by kobbe** [sensu-plugins/sensu-plugins-load-checks#6]
Hi, there are major flaws in the check, be aware when using!
- The default values are 100 times to high. The load is given on the form 0.3, 0.2, 0.1 while the settings are 75, 50, 25. I.e the loads needs to be multiplied with 100. **Using settings like 50,40,30 will never get this check to alert.**
- The exact boarders are not included. That comparisons are > and should be >=.
- The default values should be [75, 50, 25] not [25, 50, 75]. Having 25 as default value for 1 min average will always set the check off.

**Comment by majormoses** [comment]
@kobbe Taking a look I have some thoughts, questions, and feedback. I think this would be better catagorized as mostly bad defaults rather than major flaws. I would like to put together a pr to address some/all of your concerns just wanted to open up a discussion first to understand your and others concerns better before starting any work.

> The default values are 100 times to high. The load is given on the form 0.3, 0.2, 0.1 while the settings are 75, 50, 25. I.e the loads needs to be multiplied with 100. Using settings like 50,40,30 will never get this check to alert.

As the per_core option defaults to false these defaults are entirely arbitrary as I see them. This will greatly differ based on the hardware its checking against and my guess is that the author wanted to give an arbitrarily high rather than low number. I wish the defaults were per_core = true and the defaults based on this, if someone wants an arbitrary number then I think they should set it. The numbers seem 10x-20x high rather than 100x to me if split by core (which is fine as its not the default and the default is arbitrary). I think these numbers might make more sense as a default:

```
babrams@ip-172-16-250-16:~$ /opt/sensu/embedded/bin/check-load.rb -p -w 3.0,2.0,1.0 -c 7.5,5,2.5
CheckLoad CRITICAL: Load average: 3.01, 3.01, 2.99
```

This shows the machine is suffering from sustained load rather than a blip which seems actionable rather than it had a short lived surge of load (traffic). In addition I would be very interested if I had a VERY large surge in load as that is more likely to include an issue rather than a surge in traffic. Btw I am not sold on these numbers 7.5 still seems way too high for me I was simply trying to illustrate using the numbers we are using as to how those numbers would make more sense for more people.

Here are the numbers that seem to work well for my organisation:

```
babrams@ip-172-16-250-16:~$ /opt/sensu/embedded/bin/check-load.rb -p -w 2.75,2.5,2.0 -c 3.5,3.25,3.0
CheckLoad WARNING: Load average: 2.96, 3.0, 2.99
```

> The exact boarders are not included. That comparisons are > and should be >=.

Absolutely agree, its a very simple fix.

> The default values should be [75, 50, 25] not [25, 50, 75]. Having 25 as default value for 1 min average will always set the check off

Couple of things here:
- As I stated before that these numbers are kinda arbitrary without knowing how many cores are under the hood.
- I agree see comments above.

Does this make sense? If so I will work on putting together a pr for this. @eheydrick  @analytically @cwjohnston what are your thoughts on this?

**Comment by confiq** [comment]
@majormoses I think you just need little bit better docs...

**Comment by majormoses** [comment]
@confiq what would you like to see added as far as doc goes to the pr?

**Comment by confiq** [comment]
usage on README.md. 
I personally had to look at the code and understand what's going on... it would be nice to see it on README.md

**Comment by majormoses** [comment]
@confiq added some doc let me know if there is something else you would like to see

**Comment by confiq** [comment]
you even added -p to be True!
Much better! 
(Reminder that I'm not OP, I understand what this plugin does. I'm not pointing that this plugin has "major flaws", it just misses docs). Again, great work!
